disabled_rules:
- trailing_whitespace
- identifier_name
- type_name
- force_cast
- force_unwrapping
- shorthand_operator
- multiple_closures_with_trailing_closure

force_cast: warning
line_length: 140

excluded:
- Tuist/
